quarkus.qute.alt-expr-syntax=true

site.url=https://edewit.github.io/keycloak-frontend-tools

site.collections.projects.layout=project
site.collections.projects.from-data.id-key=id
site.collections.projects.link=/projects/:slug/
