quarkus.qute.alt-expr-syntax=true

site.url=https://edewit.github.io
quarkus.http.root-path=/keycloak-frontend-tools

site.collections.projects.layout=project
site.collections.projects.from-data.id-key=id
site.collections.projects.link=/projects/:slug/

site.collections.posts.layout=post
site.collections.posts.link=/blog/:slug/
